### model
model_name_or_path: /path/to/your/checkpoint/Qwen3-VL-8B-Instruct
image_max_pixels: 401408

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: 
  - kvg-cot-sft-aircraft-72B
  - kvg-cot-sft-car-72B
  - kvg-cot-sft-reptilia-72B
  - kvg-cot-sft-bird-32B
  - kvg-cot-sft-food-sam3-v1-32B
template: qwen3_vl
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16

### output
run_name: qwen3-kvg-cot-sft
output_dir: /path/to/your/output/directory
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 2.0e-6
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
